name: cardioception
dependencies:
  - python=3.9
  - pip
  - conda-forge::pymc=5.6.0
  - conda-forge::wxpython=4.2.0
  - pip:
    - systole-core>=0.3.0
    - psychopy==2022.2.5
    - cardioception-toolbox
    - metadpy