name: cardioception
dependencies:
  - python=3.9
  - pip
  - conda-forge::pymc=5.6.0
  - conda-forge::wxpython=4.2.0
  - pip:
    - bokeh==2.4.3
    - systole==0.2.4
    - psychopy==2022.2.5
    - cardioception
    - metadpy